[package]
name = "random-world"
version = "0.1.0"
authors = ["Giovanni Cherubin <giovanni.cherubin@gmail.com>"]

[dependencies]
rand = "0.3"
rayon = "0.8.2"
pcg_rand = "0.7.0"
itertools = "0.6.2"
ordered-float = "0.5.0"
rusty-machine = "0.5.4"
lazysort = "0.1.1"
ndarray = "0.10.0"
