[package]
name = "random-world"
version = "0.1.0"
authors = ["Giovanni Cherubin <g.chers@gmail.com>"]

[dependencies]
rand = "0.3"
pcg_rand = "0.7.0"
itertools = "0.6.2"
ordered-float = "0.5.0"
rusty-machine = "0.5.4"
ndarray = "0.10.0"
